### ISSUE TITLE
内製Wrapper で GPT-4, GPT-3.5, Gemini に対応する

### ISSUE THREAD

**Issue by m1sk9** [approvers/ichiyoAI#163]
https://ai.google.dev/docs/gemini_api_overview#chat

**Comment by Nanai10a** [comment]
- 生成 AI のラッパを作ります
  - GPT-\* と Gemini に対応させます
  - DALL-E は要らないかな
- ロジックを置き換えます
  - ついでに治したかった挙動のいくつかも直したい
  - が, 大筋は壊したくない (必要がないから)
-  動作確認
  - Gemini は私でも出来るけど GPT-\* はなァ
- 対応完了

タスクがデカいので task list 立てて順々に終わらせる感じになる気がします …それで良いですか？ @m1sk9

**Comment by m1sk9** [comment]
> - 生成 AI のラッパを作ります
> 
>   - GPT-\* と Gemini に対応させます
> 
>   - DALL-E は要らないかな

この場合 ichiyoAI 基準のラッパかそうではないかで話が変わりそうだな.

一応ラッパの所有権は approvers でいいかな？

> 
> - ロジックを置き換えます
> 
>   - ついでに治したかった挙動のいくつかも直したい
> 
>   - が, 大筋は壊したくない (必要がないから)

問題しかないので全然大筋破壊してそれこそ ichiyoAI v2 としてリリースしてもいい（笑）

> 
> -  動作確認
> 
>     - Gemini は私でも出来るけど GPT-\* はなァ
> 
> - 対応完了
> 
> 
> 
> タスクがデカいので task list 立てて順々に終わらせる感じになる気がします …それで良いですか？ @m1sk9 

いいよ

@Nanai10a
